### ISSUE TITLE
What's the difference between the classes GeoLocation and GeoPoint?

### ISSUE THREAD

**Issue by forger** [anthonymartin/GeoLocation-PHP#15]
Hey Anthony,

looking at the source I'm stumbling across the classes GeoLocation and GeoPoint. What's the difference? They seem redundant - am I missing something? Feel free to just update the source documentation and/or readme instead of explaining it here.

Thank you for your efforts :)

**Comment by anthonymartin** [comment]
Hey @forger - good question. The GeoLocation class is a relic from a previous version. I left it in the source code for backwards compatibility in case people upgraded the package and their implementations broke.

Instead of having everything in a monolithic class, I refactored the GeoLocation class into domain specific classes: Earth, BoundingBox, GeoPoint, Polygon. This makes it easier for maintainability and understanding what's actually going on.

**Comment by forger** [comment]
I see! Thanks, it all makes sense now :) Keep up the good work <3
